import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MuseoModerno } from "next/font/google";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
const inter = Inter({ subsets: ["latin"] });
const museoModerno = MuseoModerno({ subsets: ["latin"], weight: ["600"], variable: "--font-museoModerno" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${museoModerno.className}`} >{children}</body>
    </html>
  );
}
